accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy


app_name = 'accounts'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/pass_change_form.html',success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/pass_change_done.html',), name='password_change_done'),
    path('users/<int:id>/profile/',views.profile,name = 'profile'),
    path('registration/',views.register, name='register'),
    path('ip_control/', views.ip_control_view, name='ip-control'),
    path('edit/',views.edit_profile, name='edit')
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('list/<slug:category_tag>/', views.ArticleListView.as_view(), name='article-list'),
    path('<slug:slug>/',views.ArticleDetailView.as_view() , name='article-detail'),
    path('article/new/', views.article_new, name='article-new'),
    path('article/edit/<slug:slug>/', views.UpdateArticleView.as_view(), name='article-edit'),
    path('article/<slug:slug>/delete/', views.DeleteArticleView.as_view(), name='article-delete'),
    path('page/administration', views.page_user_admin, name='page_administration'),
    path('allpost-json', views.posts, name='allposts-json'),
    path('postsLastHour', views.post_ultima_ora, name='posts-last-hour'),
    path('search', views.search, name="search"),


]

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [

    path('',views.BlogView.as_view() , name='blog'),


]

socialDex/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('articles/',include('articles.urls')),
    path('',include('accounts.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import  TemplateView
from django.core.paginator import Paginator
from articles.models import Article






class BlogView(TemplateView):
    template_name = 'blog/base.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles =Article.objects.filter(status='PUBLISHED')
        context['banner'] =articles[0]
        articles_list =articles[1:]
        context['articles_list'] = articles_list
        paginator = Paginator(articles_list,5)
        page_number= self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        context['categories']= Article.CATEGORIES
        return context

blog/templates/blog/partials/_banner_big.html
<div class="p-4 p-md-5 mb-4 text-dark rounded " style="background-color: #F5F5DC;">
        <div class="col-md-6 px-0">
          <h1 class="display-4 fst-italic">{{banner.title}}</h1>
          <p class="lead my-3">{{banner.content|truncatewords:15 }}</p>
          <p class="lead mb-0"><a href="{{banner.get_absolute_url}}" class="text-white fw-bold">Read More....</a></p>
        </div>
      </div>

blog/templates/blog/partials/_footer.html
<footer class="blog-footer">
    <p>Blog-chain  made by:Feranmi Ojo a student by <a href="https://talent.start2impact.it/profile/feranmi-ojo">Start2impact</a>.</p>
    <p>
      <a href="{% url 'blog:blog'%}">Back to top</a>
    </p>
  </footer>

blog/templates/blog/partials/_header.html
<header class="blog-header py-3">
      {% block header_top %}
      {% include "blog/partials/_header_top.html" %}
      {% endblock %}


      <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </header>

blog/templates/blog/partials/_header_top.html
<div class="row flex-nowrap justify-content-between align-items-center">
        <div class="col-4 pt-1">

        </div>

        <div class="col-4 text-center">
            {% if user.is_authenticated %}
                <a class="blog-header-logo text-dark" href="{% url 'blog:blog'%}" >Blog-chain</a>
            {%else%}
                <a class="blog-header-logo text-dark" href="">Blog-chain</a>
            {%endif%}
        </div>
        <div class="col-4 d-flex justify-content-end align-items-center">
            {% if user.is_authenticated %}

                    <a class="btn dropdown-toggle"  href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="background-color: #F5F5DC;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="black" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                            <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z"/>
                        </svg>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                        <li><a class="dropdown-item" href="{%url 'accounts:profile' user.profile.id%}">{{user.username}}</a>
                        <li><a class="dropdown-item" href="{% url 'articles:article-new'%}" class="top-menu"><span class="glyphicon glyphicon-plus"> New Post</span> </a>
                        {%if user.is_superuser%}
                            <li><a class="dropdown-item" href="{%url 'articles:page_administration' %}">Only Admin</a></li>
                        {%endif%}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout'%}">Logout</a></li>
                    </ul>



            {%else%}
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:login'%}">Login</a>
                <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:register'%}">Registration</a>
            {%endif%}


        </div>


</div>

blog/templates/blog/partials/_landinpage_content.html
 <div class="container">
      {% block banner %}
      {% include "blog/partials/_banner_big.html"%}
      {% endblock %}

     

    <main role="main" class="container">
      <div class="row g-5">
        {% block section_articles%}
        {% include "blog/partials/_section_articles.html"%}
        {% endblock %}

        {% block sidebar%}
        {% include "blog/partials/_sidebar.html"%}
        {% endblock %}

      </div>
    </main>

</div>

blog/templates/blog/partials/_pagination.html
<nav class="blog-pagination" aria-label="Pagination">

        {% if page.has_previous %}
            <a class="btn btn-outline-danger" href="?page=1">&laquo; first</a>
            <a class="btn btn-outline-danger" href="?page={{ page.previous_page_number }}">previous</a>
        {% else%}
            <a class="btn btn-outline-secondary disabled">first</a>
            <a class="btn btn-outline-secondary disabled">previous</a>
        {% endif %}


            Page {{ page.number }} of {{ page.paginator.num_pages }}.

        {% if page.has_next %}
            <a class="btn btn-outline-danger"  href="?page={{ page.next_page_number }}">next</a>
            <a class="btn btn-outline-danger"  href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
        {% else%}
            <a class="btn btn-outline-secondary disabled">next</a>
            <a class="btn btn-outline-secondary disabled">last</a>
        {% endif %}

</nav>

blog/templates/blog/partials/_section_articles.html
<div class="col-md-8">


    <h2 class="pb-4 mb-4 fst-italic border-bottom">
            Articles posted on the blog:
    </h2>
        {% block pagination2%}
            {% include "blog/partials/_pagination.html" with page=page_obj %}
        {% endblock %}



    {% for article in page_obj%}
        <article class="blog-post">
            <h2 class="blog-post-title">{{article.title}}</h2>
            <p class="blog-post-meta">{{article.published}}<strong><a href="{%url 'accounts:profile' article.author.profile.id%} " style="color:#A52A2A">{{article.author}}</a></strong></p>
            <p align="justify"> {{article.content|truncatewords:150}}  </p>
            <p class="blog-post-footer"><strong><a href="{{article.get_absolute_url}}" style="color:#A52A2A" >Read more..</a></strong></p>
        </article>
    {% endfor %}


    {% block pagination%}
    {% include "blog/partials/_pagination.html" with page=page_obj %}
    {% endblock %}


</div>

blog/templates/blog/partials/_sidebar.html
 <div class="col-md-4">
          {% block widget_about%}
          {% include "blog/partials/_widget_about.html"%}
          {% endblock %}

          {% block widget_archives%}
          {% include "blog/partials/_widget_archives.html"%}
          {% endblock %}

          {% block widget_social%}
          {% include "blog/partials/_widget_social.html"%}
          {% endblock %}


        </div>

blog/templates/blog/partials/_widget_about.html
 <div class="position-sticky " style="top: 2rem;">
            <div class="p-4 mb-3 text-dark "style="background-color: #F5F5DC;">
              <h4 class="fst-italic">About</h4>
              <p class="mb-0">
                  Would you like to see how many times a word is repeated in all published posts?
                  <br>
              </p>
                <br>
                <form action="{% url 'articles:search' %}"  method="GET" class="mb-5">
                    <input name="q"  type="search" placeholder="Search..." aria-label="Search">
                    <input  type="submit" value="Search"/>
                </form>
            </div>
 </div>

blog/templates/blog/partials/_widget_archives.html
<div class="p-4">
              <h4 class="fst-italic">Categories</h4>
               <ol class="list-unstyled mb-0">
                  {% for category_tag , category_display_name in categories %}
                    <li><a class="p-2 link-primary" href="{%url 'articles:article-list' category_tag %}" style="color:#A52A2A">{{category_display_name}}</a></li>
                  {%endfor%}
               </ol>

</div>

blog/templates/blog/partials/_widget_social.html
<div class="p-4">
              <h4 class="fst-italic">Elsewhere</h4>
              <ol class="list-unstyled" >
                <li><a href="https://github.com/feranmi-oj/Progetto-django-di-Feranmi-Ojo" style="color:#000000">GitHub</a></li>
                <li><a href="https://talent.start2impact.it/profile/feranmi-ojo"style="color:#000000">Start2Impact</a></li>
                <li><a href="https://www.facebook.com/groups/1536160093204630"style="color:#000000">Facebook</a></li>
              </ol>
</div>