accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy


app_name = 'accounts'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/pass_change_form.html',success_url=reverse_lazy('accounts:password_change_done')), name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/pass_change_done.html',), name='password_change_done'),
    path('users/<int:id>/profile/',views.profile,name = 'profile'),
    path('registration/',views.register, name='register'),
    path('ip_control/', views.ip_control_view, name='ip-control'),
    path('edit/',views.edit_profile, name='edit')
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [

    path('',views.BlogView.as_view() , name='blog'),


]

socialDex/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('articles/',include('articles.urls')),
    path('',include('accounts.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,null=True, on_delete=models.CASCADE)
    birthday = models.DateField(blank=True,null=True)
    ip_address = models.CharField(max_length=150, blank=True,null=True)

    def __str__(self):
        return "Profilo dell'utente {}".format(self.user.username)
    def get_absolute_url(self):
        return reverse('accounts:profile', kwargs={'id':self.id})

@receiver(post_save,sender=settings.AUTH_USER_MODEL)
def update_user_profile(sender,instance,created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth import get_user_model


User = get_user_model()
non_allowed_words = 'hack'


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    ip_address = forms.CharField(widget=forms.HiddenInput)




class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=40,required=False,help_text='optional')
    last_name = forms.CharField(max_length=40,required=False,help_text='optional')
    birthday = forms.DateField(required=False,help_text='optional format: yyyy-MM--DD')
    email = forms.CharField(max_length=120,help_text='Required Submit a valid email address')
    class Meta:
        model = User
        fields = ('username','first_name','last_name','birthday','email','password1','password2',)



class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email',)

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('birthday',)

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm,UserEditForm,ProfileEditForm,LoginForm
from django.contrib.auth import login,authenticate
from django.contrib import messages
from .models import Profile
from articles.models import Article

# Create your views here.

@login_required()
def ip_control_view(request):
    context = {}
    return render(request, 'registration/ip_control.html', context)

def getIpAdd(request):
    try:
        x_forward = request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forward:
            ip = x_forward.split(",")[0]
        else:
            ip = request.META.get("REMOTE_ADDR")
    except:
        ip = ""
    return ip

def login_view(request):
    ip_address = getIpAdd(request)
    initial_data = {
        'ip_address': ip_address,
    }
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
            try:
                user_info = Profile.objects.get(user=user)
            except:
                user_info = Profile.objects.create(user=user)
            user_info.save()
            ip_address = getIpAdd(request)
            if ip_address != user_info.ip_address:
                user_info.ip_address = ip_address
                user_info.save()
                return redirect(f"/ip_control/?next={next}")

            else:
                return redirect('blog/')
    else:
        form = LoginForm(initial=initial_data)
    return render(request, 'registration/login.html', {'form': form})



def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db() #stiamo andando a ricaricare l'istanza del profilo che è stata generata dal signals
            user.profile.birthday = form.cleaned_data.get('birthday')
            user.profile.ip_address= getIpAdd(request)
            user.profile.save()
            username = form.cleaned_data.get('username')
            row_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username,password=row_password)
            login(request,user)
            return redirect('accounts:profile', id=user.id)
    else:
        form = RegistrationForm()
    return render(request,'registration/registration.html',{'form':form})
def num_post(request):
    num_post = Article.objects.filter(author=request.user)
    return render(request, 'some_template.html', {'num_post': num_post})

def profile(request,id):
    user_profile = get_object_or_404(Profile, id=id)
    num_post = Article.objects.filter(author=request.user)
    return render(request, 'accounts/profile.html', {'user_profile': user_profile,'num_post':num_post})



@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            return render(request,'accounts/profile_change_done.html')
        else:
            messages.error(request,'The data entered is not valid',extra_tags='danger')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request,'registration/edit.html',
                  {'user_form': user_form,'profile_form': profile_form})

accounts/templates/accounts/profile.html
{% extends "blog/base.html" %}

{% block page_content%}

<div class="container fluid" xmlns="http://www.w3.org/1999/html">
        <h5>Info Profile:</h5>
        <div class="card vertical" style="background-color: #F5F5DC;">
            <div class="card-stacked">
                <div class="card-content">
                    <ul>
                        <li>Name: {{user_profile.user.username}}</li>
                        <li>Firstname: {{user_profile.user.first_name}}</li>
                        <li>Lastname: {{user_profile.user.last_name}}</li>
                        <li>Mail: {{user_profile.user.email}}</li>
                        <li>birthday: {{user_profile.user.profile.birthday}}</li>

                    </ul>
                    <br>
                    {% if user.username == user_profile.user.username %}
                    <p>You can edit your profile  <a href="{% url 'accounts:edit'%}" style="color:#A52A2A">here</a> </p>
                    <p> You can change your password  <a href="{% url 'accounts:password_change'%}" style="color:#A52A2A">here</a> </p>
                </div>
            </div>

        </div>
        <br>
        <br>


        <p class="pb-4 mb-4 fst-italic border-bottom" style="color:#A52A2A" >    N° Articles Published In The Blog-Chain : <a style="color:black">{{num_post.count}}</a></p>

        <div class="col s12" id="table">
            <div class="card vertical">
                <table class="table  table-bordered" style="background-color: #F5F5DC;" border = "1" cellpadding="5" cellspacing="5">
                    <thead>
                    <tr>
                        <th>Article title</th>
                        <th>category</th>
                        <th>Transaction ID post</th>
                        <th>Published date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for post in num_post %}
                    <tr>
                        <td><a href="{{post.get_absolute_url}}" style="color: black;">{{ post.title }}</a></td>
                        <td>{{post.category}}</td>
                        <td>{{ post.txId }}</td>
                        <td>{{ post.published }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {% endif %}

        <br>
        <a class="btn btn-outline-secondary" onClick="javascript:history.go(-1);">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
            </svg>
        </a>
        <a class="btn btn-outline-secondary"href="{%url 'blog:blog'%}"> Back Home</a>
    </div>


{% endblock %}

accounts/templates/accounts/profile_change_done.html
{% extends "blog/base.html" %}

{% block page_content%}

    <div class="container fluid p-5" align="center">
      <h3>Edit Profile completed successfully!</h3>
     <br>
      <h5>your profile has been modified</h5>
      <br>
      <br>
        <h6>Return to the profile by clicking here:</h6>
        <a class="btn btn-outline-secondary" href="{%url 'accounts:profile' user.profile.id%}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
            </svg>
        </a>

    </div>

{% endblock %}