articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('list/<slug:category_tag>/', views.ArticleListView.as_view(), name='article-list'),
    path('<slug:slug>/',views.ArticleDetailView.as_view() , name='article-detail'),
    path('article/new/', views.article_new, name='article-new'),
    path('article/edit/<slug:slug>/', views.UpdateArticleView.as_view(), name='article-edit'),
    path('article/<slug:slug>/delete/', views.DeleteArticleView.as_view(), name='article-delete'),
    path('page/administration', views.page_user_admin, name='page_administration'),
    path('allpost-json', views.posts, name='allposts-json'),
    path('postsLastHour', views.post_ultima_ora, name='posts-last-hour'),
    path('search', views.search, name="search"),


]

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'blog'
urlpatterns = [

    path('',views.BlogView.as_view() , name='blog'),


]

socialDex/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path('articles/',include('articles.urls')),
    path('',include('accounts.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
from.utils import sendTransaction
import hashlib
from . import wallet

# Create your models here.

class Article(models.Model):
    DRAFT= 'DRRAFT'
    PUBLISHED='PUBLISHED'
    STATUS_CHOICES=(
        (DRAFT,'Draft'),
        (PUBLISHED,'Published')
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,default=PUBLISHED)

    TECNOLOGY = 'TC'
    BLOCKCHAIN='BC'
    SPORT = 'SP'
    GENERAL_CULTURE = 'GC'
    ANIME ='AN'
    FREE_TIME = 'FT'
    CATEGORIES = [
         (TECNOLOGY,'Technology'),
        (BLOCKCHAIN,'Blockchain'),
         ( SPORT,'Sport'),
        (GENERAL_CULTURE,'General culture'),
        (ANIME ,'Anime'),
        (FREE_TIME,'Free time')
    ]
    category= models.CharField(choices= CATEGORIES,default='FT',max_length=2)
    title= models.CharField(max_length=250)
    slug= models.SlugField(max_length=250,null=False, unique=True)
    img= models.ImageField(upload_to="images/", blank=True, null=True)
    content= models.TextField(max_length=5000)
    author= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created= models.DateTimeField(default=timezone.now)
    published=models.DateTimeField(default=timezone.now)
    updated=models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=66, default=None, null=True)
    hash = models.CharField(max_length=32, default=None, null=True)
    txId = models.CharField(max_length=66, default=None, null=True)

    def writeOnChain(self):
        self.address = wallet.address
        self.hash = hashlib.sha256(self.content.encode('utf-8')).hexdigest()
        self.txId = sendTransaction(self.hash)
        self.save()


    class Meta:
        ordering = ("-updated","-published")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('articles:article-detail', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Article,self).save(*args, **kwargs)

articles/forms.py
from django import forms

from .models import Article

class ArticleEditForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title','category','img', 'content',)

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'img': forms.FileInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

articles/views.py
from django.shortcuts import render,redirect
from django.views.generic import DetailView, ListView, UpdateView,DeleteView
from .forms import ArticleEditForm
from .models import Article
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count
from django.contrib.auth.models import User
from datetime import timedelta
from django.utils.timezone import now
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page


CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)
@method_decorator(cache_page(CACHE_TTL),  name='dispatch')

class ArticleDetailView(DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context



class ArticleListView(ListView):
    model = Article
    paginate_by = 5
    def get_queryset(self):
        tag = self.kwargs.get('category_tag', None)
        queryset = Article.objects.filter(status='PUBLISHED')
        if tag:
            c = tag
            queryset = Article.objects.filter(status='PUBLISHED').filter(category__in=[tag])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Article.CATEGORIES
        tag = self.kwargs.get('category_tag', None)
        context['tag'] = tag
        return context



@login_required
def article_new(request):
    if request.method == "POST":
        forbiddenword = "hack"
        form = ArticleEditForm(request.POST, request.FILES,)
        if  forbiddenword not in request.POST['content']:
            if forbiddenword not in request.POST['title'] and form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.published = timezone.now()
                post.writeOnChain()
                post.save()
                return redirect(f'/articles/{post.slug}/',messages.success(request,"The post was successfully published "))
            else:
                messages.error(request,"The data entered is not valid, remember that the word 'hack' is prohibited in the post ")

        else:
            messages.error(request,"The data entered is not valid, remember that the word 'hack' is prohibited in the post ")

    else:
        form = ArticleEditForm()

    return render(request, 'articles/article_new.html', {'form': form}, )


class UpdateArticleView(UpdateView):
    model = Article
    form_class = ArticleEditForm
    template_name = 'articles/article_edit.html'
    def form_valid(self, form):
        forbiddenword = "hack"
        if  forbiddenword not in self.request.POST['content'] :
            if forbiddenword not in self.request.POST['title']:
                form.instance.author = self.request.user
                messages.success(self.request, "The post was successfully edited ")
                return super().form_valid(form)
            else:
                messages.error(self.request,"The data entered is not valid, remember that the word 'hack' is prohibited in the post ")
        else:
            messages.error(self.request,"The data entered is not valid, remember that the word 'hack' is prohibited in the post ")
        return render(self.request, 'articles/article_edit.html', {'form': form}, )


class DeleteArticleView(DeleteView):
    model = Article
    template_name = 'articles/article_delete.html'
    success_url = reverse_lazy("blog:blog")


def page_user_admin(request):
    users = User.objects.all().annotate(post_count=Count('article'))
    context = {'users': users}
    return render(request, 'articles/page_administration.html',  context)


def search(request):
    if "q" in request.GET:
        querystring = request.GET.get("q")
        if len(querystring) == 0:
            return redirect("/search/")
        posts = Article.objects.filter(content__icontains=querystring)
        context = {"posts": posts, "querystring": querystring}
        return render(request, "articles/search.html", context)
    else:
        return render(request, "articles/search.html")



def posts(request):
    response = []
    posts = Article.objects.filter().order_by('published')
    for post in posts:
        response.append(
            {
                'published' :f"{post.published}",
                'title':f"{post.title}",
                'slug':f"{post.slug}",
                'author':f"{post.author}",
                'content':f"{post.content}",
                'image':f"{post.img}",
                'created':f"{post.created}",
                'updated':f"{post.updated}",
                'hash': f"{post.hash}",
                'txId': f"{post.txId}"
            }
        )
    return JsonResponse(response, safe=False,json_dumps_params={'indent': 2})

def post_ultima_ora(request):
    response= []
    dt = now()
    posts_last_hour1= Article.objects.filter(published__range=(dt-timedelta(hours=1), dt))
    for post in posts_last_hour1:
        response.append(
            {
                'published' :f"{post.published}",
                'title':f"{post.title}",
                'slug':f"{post.slug}",
                'author':f"{post.author}",
                'content':f"{post.content}",
                'image':f"{post.img}",
                'created':f"{post.created}",
                'updated':f"{post.updated}",
                'hash': f"{post.hash}",
                'txId': f"{post.txId}"
            }
        )
    return JsonResponse(response, safe=False,json_dumps_params={'indent': 2})

articles/templates/articles/article_delete.html
{% extends "blog/base.html" %}
{% block page_content %}
<h1>Delete Article....</h1>
<br/>
<div class="container" align="center">
    <div class="card vertical" style="background-color: #F5F5DC;">
        <div class="card-stacked">
            <div class="card-content">
                <form method="POST">
                    {% csrf_token %}
                    <h4>Are you sure?</h4><br/>
                    <p><strong>Are you sure you want to delete the article "{{article.title}}"?</strong></p>
                    <input type="submit" class="btn btn-danger" value="Yes, i'm sure">
                    <a  class="btn btn-secondary" href="{%url 'articles:article-edit' object.slug%}">No, take me back</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}

articles/templates/articles/article_detail.html
{% extends "blog/base.html" %}
{% block page_content %}
    {% if messages %}
    {% for message in messages%}
      <div class="alert alert-success" role="alert">
          {{message}}
      </div>
    {% endfor %}
  {%endif%}
    <div class="container">
        <br>
        <br>
        {% if user == article.author%}
        <table>
            <td><h1>{{ article.title }}</h1></td>
            <td><aside class="actions">
            <a class="btn btn-default" href="{%url 'articles:article-edit' object.slug%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                    <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
                </svg>
            </a>
            </aside></td>

        </table>
        {%endif%}
        <i><strong>CATEGORY: {{article.category}} </strong></i>
        {% if object.img %}
        <div class="text-center">
        <img src="{{object.img.url}}" style="width: 500px" class="wp-caption aligncenter" alt="..." >
        </div>
        {%endif%}
        <br>
        <br>
        <p align="justify">{{ article.content }}</p>
        <p>Author: {{ article.author }}</p>
        <p>Published: {{ article.published|date }}</p>
        <p>ID: <a href="">{{ article.id }}</a></p>
        <br>

        <a class="btn btn-outline-secondary" onClick="javascript:history.go(-1);">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
            </svg>
        </a>
        <a class="btn btn-outline-secondary"href="{%url 'blog:blog'%}"> Back Home</a>
    </div>
{% endblock %}

articles/templates/articles/article_edit.html
{% extends 'blog/base.html' %}

{% block page_content %}
    {% if messages %}
    {% for message in messages%}
    <div class="alert alert-danger" role="alert">
        {{message}}
    </div>
    {% endfor %}
    {%endif%}
    <table>
        <td><h1>Edit Post ...</h1></td>
        <td><a class="btn btn-danger" href="{%url 'articles:article-delete' object.slug%}"> Delete Article</a></td>
    </table>
     <div class="form-group">
         <form method="POST" class="form-control" enctype="multipart/form-data" style="background-color: #F5F5DC;">
             {% csrf_token %}
             {{form.media}}
             {{ form.as_p }}
             <div class="d-grid gap-2" >
                <input type="submit" class="save btn btn-outline-secondary" value="Save">
             </div>
             <br>
            <br>
            <a class="btn btn-outline-secondary" href="{%url 'articles:article-detail' object.slug%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
                </svg>
            </a>

         </form>
     </div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends "blog/base.html" %}
{% block page_content %}
    {% include "articles/partials/_list_content.html" %}
{% endblock %}

articles/templates/articles/article_new.html
{% extends 'blog/base.html' %}

{% block page_content %}
    {% if messages %}
    {% for message in messages%}
    <div class="alert alert-danger" role="alert">
        {{message}}
    </div>
    {% endfor %}
    {%endif%}
     <h1>New Post ...</h1>
     <div class="form-group"  >
         <form method="POST" class="form-control" enctype="multipart/form-data"  style="background-color: #F5F5DC;">
             {% csrf_token %}
             {{form.media}}
             {{ form.as_p }}
             <div class="d-grid gap-2" >
                <input type="submit" class="save btn btn-outline-secondary" value="Save">
             </div>
             <br>
             <br>
             <a class="btn btn-outline-secondary" href="{%url 'blog:blog'%}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
                </svg>
            </a>
         </form>
     </div>

{% endblock %}

articles/templates/articles/page_administration.html
{% extends 'blog/base.html' %}

{% block page_content %}
    <h1>Page administrator</h1>
    <br>
    <div class="btn-group btn-group-toggle btn-outline" data-toggle="buttons">
      <label class="btn "style="background-color: #F5F5DC;">
           <a class="btn " href="{%url 'articles:allposts-json' %}">Json All Post</a>
      </label>
      <label class="btn "style="background-color: #F5F5DC;">
          <a class="btn " href="{%url 'articles:posts-last-hour' %}"> Json Post last1h</a>
      </label>
    </div>
    <br>
    <br>
    <table class="table  table-bordered" style="background-color: #F5F5DC;" border = "1" cellpadding="5" cellspacing="5">
        <th scope="col">User</th>
        <th scope="col">email</th>
        <th scope="col">ip address</th>
        <th scope="col">published articles</th>

       {% for user in users %}
         <tr>
             <td>{{ user }}</td>
             <td>{{user.email}}</td>
             <td>{{user.profile.ip_address}}</td>
             <td>{{ user.post_count }}</td>
         </tr>
        {% endfor %}
    </table>
     <a class="btn btn-outline-secondary" href="{%url 'blog:blog'%}">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
        </svg>
    </a>
{% endblock %}

articles/templates/articles/search.html
{% extends 'blog/base.html' %}



{% block page_content %}
    <h2 class="mt-3">Search Results</h2>
    <hr>
  <div class="d-flex d-flex flex-column justify-content-center align-items-center">
      <div class="p-4 mb-3 text-dark "style="background-color: #F5F5DC;">
          <h6>Word Check</h6>
          <form action="{% url 'articles:search' %}"  method="GET" class="mb-5">
                <input name="q"  type="search" placeholder="Search..." aria-label="Search">
                <input  type="submit" value="Search"/>
            </form>
          <h6><strong>Number of posts that contains</strong></h6>
          {% if posts %}
                <h5 align="center">"{{ querystring }}" is : {{ posts.count }}</h5>
          {% else %}
            <p class="text-muted">---</p>
          {% endif %}

      </div>
      <a class="btn btn-outline-secondary" href="{%url 'blog:blog'%}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
            </svg>
      </a>
</div>

{% endblock  %}